/* eslint-disable @next/next/no-img-element */

/**
 * El Regista logo: the yellow "EL" tag and REGISTA in our own lettering.
 * The SVGs are generated by scripts/brand/build_logo.py.
 */
export function Logo({
  size = 28,
  withWordmark = true,
  tone = "light",
}: {
  size?: number;
  withWordmark?: boolean;
  tone?: "dark" | "light";
}) {
  if (!withWordmark) {
    return <img src="/brand/icon.svg" alt="El Regista" width={size} height={size} />;
  }
  // The wordmark is 5.44 times wider than tall.
  return (
    <img
      src={tone === "dark" ? "/brand/logo-dark.svg" : "/brand/logo-light.svg"}
      alt="El Regista"
      height={size}
      width={Math.round(size * 5.44)}
      style={{ height: size, width: "auto" }}
    />
  );
}
